### ISSUE TITLE
Inverse of a matrix

### ISSUE THREAD

**Issue by gocanal** [PasaLab/marlin#6]
Hello,
Looking at the source code, there is a comment in DenseVecMatrix for the inverse method (line 570: "get the inverse of the triangular matrix"). But I think since we support LU decomposition, we can inverse a non-triangular square matrix right ?

And also, the matrix inverse and multiplication is 'out-of-core' - that means the calculation is not limited to the available physical memory, am I correct ? I have a fairly large matrix (1 million x 1 million, double precision)

thank you for sharing the code,
canal

**Comment by Myasuka** [comment]
Hi @gocanal , it's our mistake to attach incorrect comments, actually the correct comment here should be "`get the inverse of a square matrix`". Thank you for your effort.

Currently, Marlin focus on distributed dense matrix, a fairly large matrix in double precision with `1 million x 1 million` size is too large to handle as the shuffle stage, introduced in replicating blocks across the cluster, pushes too much pressure on JVM memory, disk I/O and network communication.
Maybe distributed sparse matrix is one alternative solution, and supporting distributed sparse matrix has been recorded in our roadmap.
