### ISSUE TITLE
error when compiling from master branch

### ISSUE THREAD

**Issue by gocanal** [PasaLab/marlin#7]
## Saw an error when compiling from the master branch:

MatrixSuite.scala:306: type mismatch;
found : Int (2)
required: (Int, Int, Int)
[ERROR] var result = ma.multiply(denVecMat, 2)
                                                                          ^
## one error found

I think it should be something like:
    val result = ma.multiply(denVecMat, (2, 2, 2))

canal

**Comment by Myasuka** [comment]
Really sorry for this error, we have fixed it by adding method in `BlockMatrix` which is simliar to that in `DenseVecMatrix`
